apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  labels:
    app: monitor
spec:
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: monitor
        image: 0yukali0/node-monitor:v0.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: app
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 30
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: node-exporter
  labels:
    release: {{ .Release.Name }}
spec:
  jobLabel: node-exporter
  selector:
    matchLabels:
      app: monitor
  namespaceSelector:
    matchNames:
      - default
  podMetricsEndpoints:
  - port: app
    path: /metrics
    interval: 30s
