FROM ubuntu:20.04 AS builder
RUN apt-get update && \
    apt-get install -y wget build-essential gcc libc6-dev && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /build
RUN wget https://golang.org/dl/go1.23.5.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.23.5.linux-amd64.tar.gz && \
    rm go1.23.5.linux-amd64.tar.gz
ENV PATH="/usr/local/go/bin:${PATH}"
COPY . .
RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o app .

FROM alpine
COPY --from=builder /build/app /app
ENTRYPOINT ["/app"]
